// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_wMa9osobZlN4G_yv-HIOzWT8fhZBOI',
    appId: '1:625129709642:web:13a72c9100af235dabc6b3',
    messagingSenderId: '625129709642',
    projectId: 'personai-firebase',
    authDomain: 'personai-firebase.firebaseapp.com',
    storageBucket: 'personai-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8cWDdCDLYH8W3lL9s-ZKVZjv0_Nvc5Fs',
    appId: '1:625129709642:android:1b8ed49c69e09ba4abc6b3',
    messagingSenderId: '625129709642',
    projectId: 'personai-firebase',
    storageBucket: 'personai-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhvTjnoCkZWFLEiIYEZwSFQP1cp_Ysp3o',
    appId: '1:625129709642:ios:0efdc4a54d13409cabc6b3',
    messagingSenderId: '625129709642',
    projectId: 'personai-firebase',
    storageBucket: 'personai-firebase.firebasestorage.app',
    iosBundleId: 'com.example.personai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhvTjnoCkZWFLEiIYEZwSFQP1cp_Ysp3o',
    appId: '1:625129709642:ios:0efdc4a54d13409cabc6b3',
    messagingSenderId: '625129709642',
    projectId: 'personai-firebase',
    storageBucket: 'personai-firebase.firebasestorage.app',
    iosBundleId: 'com.example.personai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk_wMa9osobZlN4G_yv-HIOzWT8fhZBOI',
    appId: '1:625129709642:web:5ee27134a2a7f4c7abc6b3',
    messagingSenderId: '625129709642',
    projectId: 'personai-firebase',
    authDomain: 'personai-firebase.firebaseapp.com',
    storageBucket: 'personai-firebase.firebasestorage.app',
  );
}
